# Generated by Django 2.2 on 2020-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=10)),
                ('contactno', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=12)),
                ('gstn', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
