# Generated by Django 2.2 on 2020-10-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Category'),
        ),
    ]
