# Generated by Django 2.2 on 2020-10-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201001_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_id', models.AutoField(db_column='ord_id', primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_price', models.FloatField()),
                ('prod_Qty', models.IntegerField()),
                ('Tot_Price', models.IntegerField()),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prod_profile',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(),
        ),
    ]
