# Generated by Django 2.2 on 2020-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201002_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ord_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Tot_Price',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('bill_id', models.AutoField(db_column='bill_id', primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('Tot_Price', models.IntegerField()),
                ('address', models.TextField()),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='AssignOrder',
            fields=[
                ('Assign_id', models.AutoField(db_column='Assign_id', primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Orders')),
            ],
            options={
                'db_table': 'AssignOrder',
            },
        ),
    ]
