# Generated by Django 2.2 on 2020-10-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Tot_Price',
            new_name='prod_Qty',
        ),
    ]
