# Generated by Django 2.2 on 2020-10-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201004_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Orders'),
        ),
    ]
