# Generated by Django 2.2 on 2020-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201004_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'Credit/Debit Card'), ('2', 'Net Banking'), ('3', 'Cash On Delivery')], max_length=25),
        ),
    ]
