# Generated by Django 2.2 on 2020-10-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201005_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Mode', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Payment_Mode'),
        ),
    ]
