# Generated by Django 2.2 on 2020-10-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201010_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(max_length=22),
        ),
    ]
