# Generated by Django 2.2 on 2020-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201010_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='userId',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Customer',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='userId',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='assignorder',
            name='Vendor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Customer',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Product',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
