# Generated by Django 2.2 on 2020-10-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201012_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='userId',
            new_name='Cust_Id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='userId',
            new_name='Cust_Id',
        ),
    ]
