# Generated by Django 2.2 on 2020-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201012_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
