# Generated by Django 2.2 on 2020-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_invoice_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='assignorder',
            name='bill_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
