# Generated by Django 2.2 on 2020-11-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201015_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_M',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('prod_id', models.CharField(max_length=6, unique=True)),
                ('prod_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Product_M',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product_M'),
        ),
    ]
